import { StyleSheet } from 'react-native';
import { Theme } from '../styles/MainTheme';
import {
  FULL_WIDTH_WITH_PADDING,
  HEADER_BAR_PADDING,
  ROUND_BUTTON_HEIGHT,
} from '../Constants';
export default StyleSheet.create({
  actionBar: {
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
  },
  actionBarText: {
    backgroundColor: 'transparent',
    fontSize: 25,
    width: '100%',
  },
  topTotalAsset: {
    fontSize: 24,
    // width: '100%',
    marginLeft: 16,
    marginTop: 2,
    // fontWeight: 'bold',
  },
  container: {
    backgroundColor: Theme.colors.background,
    flex: 1,
  },
  footer: {
    height: 100,
    alignItems: 'stretch',
    paddingHorizontal: 32,
    // paddingTop: 8,
    paddingBottom: 16,
  },
  bottomContainer: {
    // justifyContent: 'space-between',
    // alignItems: 'center',
    flex: 1,
    backgroundColor: Theme.colors.background,
    paddingBottom: 10,
  },
  badgeBubble: {
    marginTop: 4,
    marginLeft: 5,
    height: 12,
    width: 17,
    borderRadius: 4.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: Theme.colors.text,
    fontSize: 9,
    fontWeight: 'bold',
    backgroundColor: 'transparent',
    top: -0.5,
  },
  cardTitle: {
    color: Theme.colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  cardSubTitle: {
    color: Theme.colors.text,
    fontSize: 12,
    marginTop: 3,
    opacity: 0.5,
  },
  cardDesc: {
    color: Theme.colors.text,
    marginLeft: 15,
    fontSize: 12,
    marginTop: 0,
    opacity: 0.5,
  },
  cardDescHorizontal: {
    color: 'white',
    fontSize: 12,
    marginLeft: 5,
    opacity: 0.5,
  },
  detailBackgroundImage: {
    borderRadius: 0,
    padding: 0,
    paddingLeft: 0,
    alignItems: 'flex-start',
    flex: 0,
    paddingBottom: 20,
    // minHeight: 180,
  },
  detailCardPattern: { left: 30, top: 35, position: 'absolute', overflow: 'hidden', bottom: 100 },
  topSecLabel: {
    color: 'white',
    fontSize: 16,
    opacity: 0.5,
    marginHorizontal: 16,
  },
  secLabel: {
    color: 'white',
    fontSize: 14,
    opacity: 0.35,
  },
  secHeaderLabel: {
    color: 'white',
    fontSize: 14,
    opacity: 0.35,
  },
  secLabelInput: {
    color: 'white',
    fontSize: 20,
    opacity: 0.2,
    marginBottom: 15,
  },
  secLabelInputDesc: {
    color: 'white',
    fontSize: 16,
    marginBottom: 15,
  },
  secContent: {
    color: 'white',
    fontSize: 14,
    flexShrink: 1,
  },
  inputError: {
    color: Theme.colors.error,
    fontSize: 12,
    marginTop: 5,
  },
  inputAvailableValue: {
    color: Theme.colors.primary,
    fontSize: 12,
    marginTop: 5,
  },
  secContentFade: {
    color: 'white',
    fontSize: 14,
    opacity: 0.35,
  },
  currencyTextMain: {
    color: 'white',
    fontSize: 20,
    maxWidth: '60%',
    fontWeight: '500',
    marginLeft: 10,
  },
  mainNumText: {
    color: 'white',
    fontSize: 24,
    maxWidth: '60%',
    fontWeight: '500',
    alignSelf: 'center',
    textAlign: 'center',
  },
  convertedNumText: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    opacity: 0.7,
  },
  numContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    // marginTop: 10,
    marginRight: 40,
    // backgroundColor: 'red'
  },
  bottomButton: {
    // position: 'absolute',
    marginBottom: 36,
    marginTop: 16,
    alignSelf: 'center',
    height: ROUND_BUTTON_HEIGHT,
    width: '90%',
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
  },
  form: {
    padding: 16,
  },
  input: {
    fontSize: 14,
    color: 'white',
    flexShrink: 1,
    flex: 1,
    backgroundColor: 'transparent',
  },
  inputDesc: {
    fontSize: 12,
    color: 'white',
    flexShrink: 1,
    flex: 1,
    backgroundColor: 'transparent',
    opacity: 0.5,
  },
  compoundInput: {
    backgroundColor: 'transparent',
    marginHorizontal: HEADER_BAR_PADDING,
  },
  labelBlock: {
    marginTop: 25,
    width: FULL_WIDTH_WITH_PADDING,
    // alignSelf: 'center',
    flexDirection: 'column',
    color: Theme.colors.text,
    fontSize: 14,
    opacity: 0.35,
  },
  formItem: {
    minHeight: 80,
    // marginLeft: 10,
  },
  headerLeft: { flex: 0.3 },
  headerBody: { flex: 2 },
  bottomErrorMsg: {
    alignSelf: 'center',
    color: Theme.colors.error,
    marginTop: 0,
    opacity: 0.8,
    fontSize: 14,
  },
  tag: {
    paddingVertical: 2,
    borderRadius: 10,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    alignSelf: 'stretch',
    overflow: 'hidden',
  },
  listItem: {
    borderBottomWidth: 0,
    shadowOpacity: 0,
  },
  itemLeft: {
    width: 72,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  itemBody: {
    paddingVertical: 14,
    flex: 1,
    alignItems: 'flex-start',
  },
  emptyContent: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '70%',
    backgroundColor: Theme.colors.background,
  },
  resultModalIcon: { transform: [{ translateY: -6 }] },
  bottomBoarderContainer: {
    borderBottomWidth: 1,
    borderColor: Theme.colors.divider,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 15,
    marginBottom: 8,
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
    width: 56,
    height: 56,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: Theme.colors.pickerBg,
  },
  infoBackground: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: Theme.colors.primary16,
    borderColor: Theme.colors.primary,
    padding: 8,
    borderWidth: 1,
    borderRadius: 4,
    marginTop: 24,
    marginHorizontal: 36,
    flexDirection: 'row',
  },
  inputCell: {
    borderRadius: 4,
    borderWidth: 1,
    borderColor: Theme.colors.text,
  },
  inputCellText: {
    color: 'white',
    fontSize: 16,
  },
  requestNewCodeContainer: {
    marginTop: 8,
    justifyContent: 'center',
    height: 36,
  },
  phoneInvalid: {
    fontSize: 12,
    marginTop: 8,
  },
  registerMainText: {
    fontSize: 24,
    color: Theme.colors.text,
    marginTop: 40,
    marginHorizontal: 16,
    textAlign: 'center',
  },
  registerSubText: {
    fontSize: 14,
    color: Theme.colors.text,
    marginTop: 8,
    marginHorizontal: 16,
    textAlign: 'center',
  },
  shadowSurface: {
    backgroundColor: Theme.colors.backgroundPressed,
    borderRadius: 4,// marginLeft: 12, marginRight: 16, marginVertical: 14,
    //marginHorizontal: 16,
    // zIndex: 10,
    // elevation: 10,//Android need elevation
    //shadow
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 16.0,
  },
});
